### PR TITLE
Final MileStone: Building Draft UX design for Smashing Magazine

### PR DESCRIPTION
**Pull request by AhmedTohamy01**
**This project about building a draft UX design for Smashing Magazine Website. This includes:**

- Creating sections for the main areas in the website.
- Changing the colors of these sections to different level of gray color based on their visual weight .
- Adding a font from google fonts near to what is used in the real website.
- Changing the font styles, weight and size in different areas in the draft design.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Comment by AhmedTohamy01** [comment]
Hi mike, 

Thank you for your review, but i think you didn't consider that we cloning a live website which changes its contents based on the country that you access from , for example me and my coding partner have different elements when we open the same website. 

All the elements which appears on our screen are added to the project , and please consider also that the purpose of teh project is to make a "draft" UX design, or "heat map" for the website, adding each and every single element doesn't matter in the main purpose of the project.

Thank you for understanding

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Comment by AhmedTohamy01** [comment]
Hi Addod,

Thank you for your review, actually this is a CSS Grid Rule, we cannot combine all of them in 1 rule .

For the footer links we will add it and center it.

for the <br> , This is educational project just about the UX Design, it's a draft project.  <br> or width, this is NOT from the core requirements of the project. please review the requirements of the project and you will NOT find anything about NOT using <br>

Thank you for understanding.

**Comment by addod19** [comment]
> Hi Addod,
> 
> Thank you for your review, actually this is a CSS Grid Rule, we cannot combine all of them in 1 rule .
> 
> For the footer links we will add it and center it.
> 
> for the `<br>` This is educational project just about the UX Design, it's a draft project. 
> or width, this is NOT from the core requirements of the project. please review the requirements of the project and you will NOT find anything about NOT using 
> 
> Thank you for understanding.

Kindly treat the <br> comment as optional. Thank you

**Comment by AhmedTohamy01** [comment]
Thank you Addod,

If it's optional so please approve the project :) 

Appreciate your rapid response

**Comment by addod19** [comment]
> Thank you Addod,
> 
> If it's optional so please approve the project :)
> 
> Appreciate your rapid response

You still have to center the footer links so I cannot approve it. The comment about replacing the be tag is the one am marking as optional. I hope you understand me

**Comment by AhmedTohamy01** [comment]
Thank you Addod, 

We will center the footer links now and let you know.

We really appreciate your rapid response.

**Comment by AhmedTohamy01** [comment]
Hi Addod, @addod19 

We already added the footer links and centered it.

Please Approve :)

**Comment by AhmedTohamy01** [comment]
@christianotieno  Thank you Christian my friend, Always in time :)

**Pull request merged**
